// frontend/src/components/common/Header.jsx
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import '../../styles/main.css'; // Asegúrate de que aquí estén tus estilos custom

function Header({ onShowLogin, onShowRegister }) {
  const location = useLocation()
  const navigate = useNavigate()
  const { user, logout, isAdmin } = useAuth()

  // Función para marcar el link activo
  const isActive = (path) => location.pathname === path

  const handleLogout = () => {
    if (confirm('¿Estás seguro de que quieres cerrar sesión?')) {
      logout()
      navigate('/')
    }
  }

  // Manejadores para el menú dropdown
  const handleLoginClick = (e) => {
    e.preventDefault()
    if (onShowLogin) onShowLogin()
  }

  const handleRegisterClick = (e) => {
    e.preventDefault()
    if (onShowRegister) {
        onShowRegister()
    } else {
        navigate('/register')
    }
  }

  return (
    <nav className="navbar navbar-expand-lg navbar-light fixed-top navbar-custom">
      <div className="container">
        {/* LOGO CON TUS ESTILOS */}
        <Link className="navbar-brand navbar-brand-custom" to="/">
          <i className="fas fa-mountain text-primary-custom me-2"></i>
          Buganvilla Tours
        </Link>
        
        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span className="navbar-toggler-icon"></span>
        </button>
        
        <div className="collapse navbar-collapse" id="navbarNav">
          <ul className="navbar-nav ms-auto align-items-center">
            
            {/* ENLACES PRINCIPALES (Usando nav-link-custom) */}
            <li className="nav-item">
              <Link className={`nav-link nav-link-custom ${isActive('/') ? 'active' : ''}`} to="/">
                Inicio
              </Link>
            </li>
            <li className="nav-item">
              <Link className={`nav-link nav-link-custom ${isActive('/paquetes') ? 'active' : ''}`} to="/paquetes">
                Paquetes
              </Link>
            </li>
            <li className="nav-item">
              <Link className={`nav-link nav-link-custom ${isActive('/nosotros') ? 'active' : ''}`} to="/nosotros">
                Nosotros
              </Link>
            </li>
            <li className="nav-item">
              <Link className={`nav-link nav-link-custom ${isActive('/contacto') ? 'active' : ''}`} to="/contacto">
                Contacto
              </Link>
            </li>

            {/* Link Admin (Solo si es admin) */}
            {isAdmin && (
              <li className="nav-item">
                <Link className={`nav-link nav-link-custom fw-bold text-danger ${isActive('/admin') ? 'active' : ''}`} to="/admin">
                  <i className="fas fa-user-cog me-1"></i>Admin
                </Link>
              </li>
            )}

            {/* SECCIÓN DE USUARIO / CUENTA */}
            {user ? (
              // --- ESTADO LOGUEADO ---
              <li className="nav-item dropdown ms-lg-3">
                <a 
                  className="nav-link nav-link-custom dropdown-toggle btn btn-outline-primary-custom rounded-pill px-3" 
                  href="#" 
                  role="button" 
                  data-bs-toggle="dropdown"
                >
                  <i className="fas fa-user-check me-2"></i>
                  Hola, {user.nombre ? user.nombre.split(' ')[0] : 'Usuario'}
                </a>
                <ul className="dropdown-menu dropdown-menu-end shadow-sm border-0">
                  <li>
                    <span className="dropdown-item-text small text-muted">
                      <i className="fas fa-envelope me-2"></i>{user.email}
                    </span>
                  </li>
                  <li><hr className="dropdown-divider" /></li>
                  <li>
                    <Link className="dropdown-item" to="/reservas">
                      <i className="fas fa-suitcase me-2 text-primary-custom"></i>Mis Viajes
                    </Link>
                  </li>
                  <li><hr className="dropdown-divider" /></li>
                  <li>
                    <button className="dropdown-item text-danger" onClick={handleLogout}>
                      <i className="fas fa-sign-out-alt me-2"></i>Cerrar Sesión
                    </button>
                  </li>
                </ul>
              </li>
            ) : (
              // --- ESTADO NO LOGUEADO (Botón "Cuenta") ---
              <li className="nav-item dropdown ms-lg-3">
                <a 
                  className="nav-link nav-link-custom dropdown-toggle btn btn-primary-custom text-white rounded-pill px-4" 
                  href="#" 
                  role="button" 
                  data-bs-toggle="dropdown"
                >
                  <i className="fas fa-user-circle me-2"></i>
                  Cuenta
                </a>
                <ul className="dropdown-menu dropdown-menu-end shadow-sm border-0">
                  {/* Opción 1: Iniciar Sesión (Abre Modal) */}
                  <li>
                    <button className="dropdown-item py-2 w-100 text-start" onClick={handleLoginClick}>
                      <i className="fas fa-sign-in-alt me-2 text-primary-custom"></i>
                      Iniciar Sesión
                    </button>
                  </li>
                  
                  {/* Opción 2: Registrarse (Va a página nueva) */}
                  <li>
                    <button className="dropdown-item py-2 w-100 text-start" onClick={handleRegisterClick}>
                      <i className="fas fa-user-plus me-2 text-primary-custom"></i>
                      Registrarse
                    </button>
                  </li>
                </ul>
              </li>
            )}
          </ul>
        </div>
      </div>
    </nav>
  )
}

export default Header

// frontend-angular/src/app/shared/components/header/header.component.ts
import { Component, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../../core/auth/auth.service';
import { LoginModalComponent } from '../../../features/auth/login-modal/login-modal.component';
import { RegisterModalComponent } from '../../../features/auth/register-modal/register-modal.component';
import { ProfileModalComponent } from '../../../features/auth/profile-modal/profile-modal.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule, LoginModalComponent, RegisterModalComponent, ProfileModalComponent],
  templateUrl: './header.component.html'
})
export class HeaderComponent {
  auth = inject(AuthService);
  showLoginModal = signal(false);
  showRegisterModal = signal(false);
  showProfileModal = signal(false);

  openLogin(): void { this.showLoginModal.set(true); }
  closeLogin(): void { this.showLoginModal.set(false); }
  openRegister(): void { this.showRegisterModal.set(true); }
  closeRegister(): void { this.showRegisterModal.set(false); }

  onLoginSuccess(): void {
    this.showLoginModal.set(false);
  }

  onRegisterSuccess(): void {
    this.showRegisterModal.set(false);
  }
}

<nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-custom">
  <div class="container">
    <a class="navbar-brand navbar-brand-custom" routerLink="/">
      <i class="fas fa-mountain text-primary-custom me-2"></i>
      Buganvilla Tours
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto align-items-center">
        <li class="nav-item">
          <a class="nav-link nav-link-custom" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-custom" routerLink="/paquetes" routerLinkActive="active">Paquetes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-custom" routerLink="/nosotros" routerLinkActive="active">Nosotros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-custom" routerLink="/contacto" routerLinkActive="active">Contacto</a>
        </li>
        @if (auth.isAdmin()) {
          <li class="nav-item">
            <a class="nav-link nav-link-custom fw-bold text-danger" routerLink="/admin" routerLinkActive="active">
              <i class="fas fa-user-cog me-1"></i>Admin
            </a>
          </li>
        }
      </ul>

      <div class="d-flex align-items-center gap-2 ms-lg-3">
        @if (auth.isAuthenticated()) {
          <div class="dropdown">
            <button class="btn btn-outline-primary-custom dropdown-toggle"
              type="button" data-bs-toggle="dropdown">
              <i class="fas fa-user-check me-2"></i>
              Hola, {{ auth.currentUser()?.nombre?.split(' ')?.[0] || 'Usuario' }}
            </button>
            <ul class="dropdown-menu dropdown-menu-end shadow-sm border-0">
              <li><span class="dropdown-item-text text-muted small">
                <i class="fas fa-envelope me-2"></i>{{ auth.currentUser()?.email }}
              </span></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <button class="dropdown-item" (click)="showProfileModal.set(true)">
                  <i class="fas fa-user-edit me-2 text-primary-custom"></i>Editar perfil y celular
                </button>
              </li>
              <li>
                <a class="dropdown-item" routerLink="/reservas">
                  <i class="fas fa-suitcase me-2 text-primary-custom"></i>Mis compras
                </a>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <button class="dropdown-item text-danger" (click)="auth.logout()">
                  <i class="fas fa-sign-out-alt me-2"></i>Cerrar Sesión
                </button>
              </li>
            </ul>
          </div>
        } @else {
          <button class="btn btn-outline-primary-custom" (click)="openLogin()">
            <i class="fas fa-sign-in-alt me-2"></i>Iniciar Sesión
          </button>
          <button class="btn btn-primary-custom" (click)="openRegister()">
            <i class="fas fa-user-plus me-2"></i>Registrarse
          </button>
        }
      </div>
    </div>
  </div>
</nav>

@if (showLoginModal()) {
  <app-login-modal (close)="closeLogin()" (success)="onLoginSuccess()"></app-login-modal>
}

@if (showRegisterModal()) {
  <app-register-modal (close)="closeRegister()" (success)="onRegisterSuccess()"></app-register-modal>
}

@if (showProfileModal()) {
  <app-profile-modal (close)="showProfileModal.set(false)"></app-profile-modal>
}
