// frontend/src/components/common/RegisterModal.jsx
import { useState } from 'react'
import { useAuth } from '../../context/AuthContext'

function RegisterModal({ show, onHide, onSuccess }) {
  const [formData, setFormData] = useState({
    nombre: '',
    apellido: '',
    email: '',
    telefono: '',
    password: '',
    confirmPassword: ''
  })
  const { register, isLoading } = useAuth()

  const handleInputChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: value
    }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    
    if (formData.password !== formData.confirmPassword) {
      alert('Las contraseñas no coinciden')
      return
    }

    try {
      await register({
        id: Date.now(),
        nombre: formData.nombre,
        apellido: formData.apellido,
        email: formData.email,
        telefono: formData.telefono
      })
      onSuccess()
      onHide()
    } catch (error) {
      alert('Error en el registro. Inténtalo de nuevo.')
    }
  }

  if (!show) return null

  return (
    <div 
      className={`modal fade ${show ? 'show' : ''}`} 
      style={{ display: show ? 'block' : 'none', backgroundColor: 'rgba(0,0,0,0.5)' }}
      tabIndex="-1"
    >
      <div className="modal-dialog modal-lg">
        <div className="modal-content">
          <div className="modal-header bg-primary-custom text-white">
            <h5 className="modal-title">
              <i className="fas fa-user-plus me-2"></i>Regístrate para Reservar
            </h5>
            <button 
              type="button" 
              className="btn-close btn-close-white" 
              onClick={onHide}
            ></button>
          </div>
          <div className="modal-body">
            <div className="text-center mb-4">
              <i className="fas fa-lock fa-3x text-primary-custom mb-3"></i>
              <h4>Registro Requerido</h4>
              <p className="text-muted">
                Para realizar reservas necesitas tener una cuenta. Es rápido y fácil.
              </p>
            </div>

            <form onSubmit={handleSubmit}>
              <div className="row">
                <div className="col-md-6 mb-3">
                  <label htmlFor="modal-nombre" className="form-label fw-bold">
                    Nombre *
                  </label>
                  <input 
                    type="text" 
                    className="form-control form-control-custom" 
                    id="modal-nombre"
                    name="nombre"
                    value={formData.nombre}
                    onChange={handleInputChange}
                    required 
                  />
                </div>
                <div className="col-md-6 mb-3">
                  <label htmlFor="modal-apellido" className="form-label fw-bold">
                    Apellido *
                  </label>
                  <input 
                    type="text" 
                    className="form-control form-control-custom" 
                    id="modal-apellido"
                    name="apellido"
                    value={formData.apellido}
                    onChange={handleInputChange}
                    required 
                  />
                </div>
              </div>

              <div className="row">
                <div className="col-md-6 mb-3">
                  <label htmlFor="modal-email" className="form-label fw-bold">
                    Email *
                  </label>
                  <input 
                    type="email" 
                    className="form-control form-control-custom" 
                    id="modal-email"
                    name="email"
                    value={formData.email}
                    onChange={handleInputChange}
                    required 
                  />
                </div>
                <div className="col-md-6 mb-3">
                  <label htmlFor="modal-telefono" className="form-label fw-bold">
                    Teléfono
                  </label>
                  <input 
                    type="tel" 
                    className="form-control form-control-custom" 
                    id="modal-telefono"
                    name="telefono"
                    value={formData.telefono}
                    onChange={handleInputChange}
                  />
                </div>
              </div>

              <div className="row">
                <div className="col-md-6 mb-3">
                  <label htmlFor="modal-password" className="form-label fw-bold">
                    Contraseña *
                  </label>
                  <input 
                    type="password" 
                    className="form-control form-control-custom" 
                    id="modal-password"
                    name="password"
                    value={formData.password}
                    onChange={handleInputChange}
                    required 
                  />
                </div>
                <div className="col-md-6 mb-3">
                  <label htmlFor="modal-confirmPassword" className="form-label fw-bold">
                    Confirmar Contraseña *
                  </label>
                  <input 
                    type="password" 
                    className="form-control form-control-custom" 
                    id="modal-confirmPassword"
                    name="confirmPassword"
                    value={formData.confirmPassword}
                    onChange={handleInputChange}
                    required 
                  />
                </div>
              </div>

              <div className="text-center">
                <button 
                  type="submit" 
                  className="btn btn-primary-custom btn-lg w-100"
                  disabled={isLoading}
                >
                  {isLoading ? (
                    <>
                      <div className="loading-spinner me-2"></div>
                      Creando Cuenta...
                    </>
                  ) : (
                    <>
                      <i className="fas fa-user-plus me-2"></i>
                      Crear Cuenta y Continuar
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}

export default RegisterModal

// frontend-angular/src/app/features/auth/register-modal/register-modal.component.ts
import { Component, EventEmitter, Output, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../../core/auth/auth.service';

@Component({
  selector: 'app-register-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './register-modal.component.html'
})
export class RegisterModalComponent {
  @Output() close = new EventEmitter<void>();
  @Output() success = new EventEmitter<void>();

  private fb = inject(FormBuilder);
  auth = inject(AuthService);

  form: FormGroup = this.fb.group({
    nombre: ['', [Validators.required, Validators.minLength(2)]],
    apellido: ['', [Validators.required, Validators.minLength(2)]],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]],
    telefono: ['', Validators.required],
    nacionalidad: ['', Validators.required]
  });

  loading = signal(false);
  error = signal('');

  submit(): void {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.loading.set(true);
    this.error.set('');
    this.auth.register(this.form.value).subscribe({
      next: () => {
        this.loading.set(false);
        this.success.emit();
      },
      error: (err) => {
        this.loading.set(false);
        this.error.set(err?.error?.message || 'Error al registrarse. Verifica los datos.');
      }
    });
  }

  field(name: string) { return this.form.get(name)!; }
}

<div class="modal fade show d-block" tabindex="-1" style="background: rgba(0,0,0,0.5);">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header" style="background: linear-gradient(135deg, #db2777, #be185d); color: white;">
        <h5 class="modal-title fw-bold">🌸 Crear Cuenta</h5>
        <button type="button" class="btn-close btn-close-white" (click)="close.emit()"></button>
      </div>
      <div class="modal-body p-4">
        @if (error()) {
          <div class="alert alert-danger">{{ error() }}</div>
        }
        <form [formGroup]="form" (ngSubmit)="submit()">
          <div class="row g-3">
            <div class="col-md-6">
              <label class="form-label fw-semibold">Nombre</label>
              <input type="text" formControlName="nombre" class="form-control"
                [class.is-invalid]="field('nombre').invalid && field('nombre').touched">
              @if (field('nombre').invalid && field('nombre').touched) {
                <div class="invalid-feedback">Nombre requerido (mín. 2 caracteres).</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Apellido</label>
              <input type="text" formControlName="apellido" class="form-control"
                [class.is-invalid]="field('apellido').invalid && field('apellido').touched">
              @if (field('apellido').invalid && field('apellido').touched) {
                <div class="invalid-feedback">Apellido requerido (mín. 2 caracteres).</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Email</label>
              <input type="email" formControlName="email" class="form-control"
                [class.is-invalid]="field('email').invalid && field('email').touched">
              @if (field('email').invalid && field('email').touched) {
                <div class="invalid-feedback">Email inválido.</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Contraseña</label>
              <input type="password" formControlName="password" class="form-control"
                [class.is-invalid]="field('password').invalid && field('password').touched">
              @if (field('password').invalid && field('password').touched) {
                <div class="invalid-feedback">Mínimo 6 caracteres.</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Teléfono</label>
              <input type="tel" formControlName="telefono" class="form-control"
                [class.is-invalid]="field('telefono').invalid && field('telefono').touched">
              @if (field('telefono').invalid && field('telefono').touched) {
                <div class="invalid-feedback">Teléfono requerido.</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Nacionalidad</label>
              <input type="text" formControlName="nacionalidad" class="form-control"
                [class.is-invalid]="field('nacionalidad').invalid && field('nacionalidad').touched">
              @if (field('nacionalidad').invalid && field('nacionalidad').touched) {
                <div class="invalid-feedback">Nacionalidad requerida.</div>
              }
            </div>
          </div>
          <button type="submit" class="btn w-100 fw-bold text-white mt-4" [disabled]="loading()"
            style="background: linear-gradient(135deg, #db2777, #be185d);">
            @if (loading()) { <span class="spinner-border spinner-border-sm me-2"></span> }
            Crear Cuenta
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
