// frontend/src/components/auth/RegisterModal.jsx
import { useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import { useNavigate } from 'react-router-dom'
import { authAPI } from '../../services/api'

function RegisterModal({ show, onHide, onShowLogin }) {
  const { login } = useAuth()
  const navigate = useNavigate()
  const [formData, setFormData] = useState({
    nombres: '',
    apellidos: '',
    email: '',
    password: '',
    confirmPassword: '',
    telefono: '',
    nacionalidad: 'Perú',
    aceptaTerminos: false
  })
  const [loading, setLoading] = useState(false)
  const [errors, setErrors] = useState({})

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }))
    
    // Limpiar error del campo cuando el usuario empiece a escribir
    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }))
    }
  }

  const validateForm = () => {
    const newErrors = {}

    if (!formData.nombres.trim()) {
      newErrors.nombres = 'Los nombres son requeridos'
    }

    if (!formData.apellidos.trim()) {
      newErrors.apellidos = 'Los apellidos son requeridos'
    }

    if (!formData.email.trim()) {
      newErrors.email = 'El email es requerido'
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'El email no es válido'
    }

    if (!formData.password) {
      newErrors.password = 'La contraseña es requerida'
    } else if (formData.password.length < 6) {
      newErrors.password = 'La contraseña debe tener al menos 6 caracteres'
    }

    if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = 'Las contraseñas no coinciden'
    }

    if (!formData.telefono.trim()) {
      newErrors.telefono = 'El teléfono es requerido'
    }

    if (!formData.aceptaTerminos) {
      newErrors.aceptaTerminos = 'Debes aceptar los términos y condiciones'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    
    if (!validateForm()) {
      return
    }

    setLoading(true)
    setErrors({})

    try {
      // Preparar datos para el backend
      const registerData = {
        nombre: formData.nombres,
        apellido: formData.apellidos,
        email: formData.email,
        password: formData.password,
        telefono: formData.telefono,
        nacionalidad: formData.nacionalidad
      }

      // Llamada a la API del backend
      const response = await authAPI.register(registerData)

      if (response.success && response.data) {
        const { token, usuario } = response.data
        
        // Mapear el usuario del backend al formato esperado por el frontend
        const userData = {
          id: usuario.idUsuario,
          nombre: usuario.nombre,
          apellido: usuario.apellido,
          email: usuario.email,
          telefono: usuario.telefono,
          nacionalidad: usuario.nacionalidad,
          rol: usuario.rol?.toLowerCase() || 'cliente'
        }

        // Iniciar sesión automáticamente después del registro
        login(token, userData)
        onHide()
        
        // Los clientes registrados se quedan en la página actual
      } else {
        setErrors({ submit: response.message || 'Error al crear la cuenta. Inténtalo de nuevo.' })
      }
    } catch (error) {
      console.error('Error en registro:', error)
      const errorMessage = error.response?.data?.message || 
                          error.message || 
                          'Error al crear la cuenta. Inténtalo de nuevo.'
      setErrors({ submit: errorMessage })
    } finally {
      setLoading(false)
    }
  }

  if (!show) return null

  return (
    <div 
      className={`modal fade ${show ? 'show' : ''}`} 
      style={{ display: show ? 'block' : 'none', backgroundColor: 'rgba(0,0,0,0.5)' }}
      tabIndex="-1"
    >
      <div className="modal-dialog modal-dialog-centered modal-lg">
        <div className="modal-content">
          <div className="modal-header">
            <h5 className="modal-title">
              <i className="fas fa-user-plus text-primary-custom me-2"></i>
              Crear Cuenta
            </h5>
            <button 
              type="button" 
              className="btn-close" 
              onClick={onHide}
              disabled={loading}
            ></button>
          </div>
          
          <div className="modal-body">
            {errors.submit && (
              <div className="alert alert-error-custom mb-3">
                <i className="fas fa-exclamation-triangle me-2"></i>
                {errors.submit}
              </div>
            )}

            <form onSubmit={handleSubmit}>
              <div className="row">
                <div className="col-md-6 mb-3">
                  <label htmlFor="register-nombres" className="form-label fw-bold">
                    Nombres *
                  </label>
                  <input 
                    type="text" 
                    className={`form-control form-control-custom ${errors.nombres ? 'is-invalid' : ''}`}
                    id="register-nombres"
                    name="nombres"
                    value={formData.nombres}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                  {errors.nombres && <div className="invalid-feedback">{errors.nombres}</div>}
                </div>

                <div className="col-md-6 mb-3">
                  <label htmlFor="register-apellidos" className="form-label fw-bold">
                    Apellidos *
                  </label>
                  <input 
                    type="text" 
                    className={`form-control form-control-custom ${errors.apellidos ? 'is-invalid' : ''}`}
                    id="register-apellidos"
                    name="apellidos"
                    value={formData.apellidos}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                  {errors.apellidos && <div className="invalid-feedback">{errors.apellidos}</div>}
                </div>
              </div>

              <div className="mb-3">
                <label htmlFor="register-email" className="form-label fw-bold">
                  Correo Electrónico *
                </label>
                <input 
                  type="email" 
                  className={`form-control form-control-custom ${errors.email ? 'is-invalid' : ''}`}
                  id="register-email"
                  name="email"
                  value={formData.email}
                  onChange={handleInputChange}
                  disabled={loading}
                />
                {errors.email && <div className="invalid-feedback">{errors.email}</div>}
              </div>

              <div className="row">
                <div className="col-md-6 mb-3">
                  <label htmlFor="register-password" className="form-label fw-bold">
                    Contraseña *
                  </label>
                  <input 
                    type="password" 
                    className={`form-control form-control-custom ${errors.password ? 'is-invalid' : ''}`}
                    id="register-password"
                    name="password"
                    value={formData.password}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                  {errors.password && <div className="invalid-feedback">{errors.password}</div>}
                </div>

                <div className="col-md-6 mb-3">
                  <label htmlFor="register-confirm-password" className="form-label fw-bold">
                    Confirmar Contraseña *
                  </label>
                  <input 
                    type="password" 
                    className={`form-control form-control-custom ${errors.confirmPassword ? 'is-invalid' : ''}`}
                    id="register-confirm-password"
                    name="confirmPassword"
                    value={formData.confirmPassword}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                  {errors.confirmPassword && <div className="invalid-feedback">{errors.confirmPassword}</div>}
                </div>
              </div>

              <div className="row">
                <div className="col-md-6 mb-3">
                  <label htmlFor="register-telefono" className="form-label fw-bold">
                    Teléfono *
                  </label>
                  <input 
                    type="tel" 
                    className={`form-control form-control-custom ${errors.telefono ? 'is-invalid' : ''}`}
                    id="register-telefono"
                    name="telefono"
                    value={formData.telefono}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                  {errors.telefono && <div className="invalid-feedback">{errors.telefono}</div>}
                </div>

                <div className="col-md-6 mb-3">
                  <label htmlFor="register-nacionalidad" className="form-label fw-bold">
                    Nacionalidad
                  </label>
                  <select 
                    className="form-select form-control-custom"
                    id="register-nacionalidad"
                    name="nacionalidad"
                    value={formData.nacionalidad}
                    onChange={handleInputChange}
                    disabled={loading}
                  >
                    <option value="Perú">Perú</option>
                    <option value="Argentina">Argentina</option>
                    <option value="Chile">Chile</option>
                    <option value="Colombia">Colombia</option>
                    <option value="Ecuador">Ecuador</option>
                    <option value="México">México</option>
                    <option value="España">España</option>
                    <option value="Estados Unidos">Estados Unidos</option>
                    <option value="Otro">Otro</option>
                  </select>
                </div>
              </div>

              <div className="mb-3 form-check">
                <input 
                  type="checkbox" 
                  className={`form-check-input ${errors.aceptaTerminos ? 'is-invalid' : ''}`}
                  id="acepta-terminos"
                  name="aceptaTerminos"
                  checked={formData.aceptaTerminos}
                  onChange={handleInputChange}
                  disabled={loading}
                />
                <label className="form-check-label" htmlFor="acepta-terminos">
                  Acepto los <a href="#" className="text-primary-custom">Términos y Condiciones</a> y las <a href="#" className="text-primary-custom">Políticas de Privacidad</a> *
                </label>
                {errors.aceptaTerminos && <div className="invalid-feedback d-block">{errors.aceptaTerminos}</div>}
              </div>

              <div className="d-grid gap-2">
                <button 
                  type="submit" 
                  className="btn btn-primary-custom"
                  disabled={loading}
                >
                  {loading ? (
                    <>
                      <div className="loading-spinner me-2"></div>
                      Creando Cuenta...
                    </>
                  ) : (
                    <>
                      <i className="fas fa-user-plus me-2"></i>
                      Crear Cuenta
                    </>
                  )}
                </button>
              </div>
            </form>

            <div className="text-center mt-3">
              <button 
                className="btn btn-link p-0 text-primary-custom"
                onClick={onShowLogin}
                disabled={loading}
              >
                ¿Ya tienes cuenta? Inicia sesión aquí
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default RegisterModal

// frontend-angular/src/app/features/auth/register-modal/register-modal.component.ts
import { Component, EventEmitter, Output, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../../core/auth/auth.service';
import { NATIONAL_PHONE_PATTERN, PHONE_COUNTRIES, toE164 } from '../../../shared/data/phone-countries';

@Component({
  selector: 'app-register-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './register-modal.component.html'
})
export class RegisterModalComponent {
  @Output() close = new EventEmitter<void>();
  @Output() success = new EventEmitter<void>();

  private fb = inject(FormBuilder);
  auth = inject(AuthService);
  countries = PHONE_COUNTRIES;

  form: FormGroup = this.fb.group({
    nombre: ['', [Validators.required, Validators.minLength(2)]],
    apellido: ['', [Validators.required, Validators.minLength(2)]],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(8)]],
    prefijoTelefono: ['+51', Validators.required],
    telefono: ['', [Validators.required, Validators.pattern(NATIONAL_PHONE_PATTERN)]],
    nacionalidad: ['Perú', Validators.required]
  });

  loading = signal(false);
  error = signal('');

  submit(): void {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.loading.set(true);
    this.error.set('');
    const value = this.form.value;
    const request = {
      nombre: value.nombre,
      apellido: value.apellido,
      email: value.email,
      password: value.password,
      telefono: toE164(value.prefijoTelefono, value.telefono),
      nacionalidad: value.nacionalidad
    };
    this.auth.register(request).subscribe({
      next: () => {
        this.loading.set(false);
        this.success.emit();
      },
      error: (err) => {
        this.loading.set(false);
        this.error.set(err?.error?.message || 'Error al registrarse. Verifica los datos.');
      }
    });
  }

  field(name: string) { return this.form.get(name)!; }
}

<div class="modal fade show d-block" tabindex="-1" style="background: rgba(0,0,0,0.5);">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title fw-bold">
          <i class="fas fa-user-plus text-primary-custom me-2"></i>
          Crear Cuenta
        </h5>
        <button type="button" class="btn-close" (click)="close.emit()" [disabled]="loading()"></button>
      </div>
      <div class="modal-body p-4">
        @if (error()) {
          <div class="alert-error-custom mb-3">
            <i class="fas fa-exclamation-triangle me-2"></i>{{ error() }}
          </div>
        }
        <form [formGroup]="form" (ngSubmit)="submit()">
          <div class="row g-3">
            <div class="col-md-6">
              <label class="form-label fw-semibold">Nombre *</label>
              <input type="text" formControlName="nombre" class="form-control form-control-custom"
                [class.is-invalid]="field('nombre').invalid && field('nombre').touched">
              @if (field('nombre').invalid && field('nombre').touched) {
                <div class="invalid-feedback">Nombre requerido (mín. 2 caracteres).</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Apellido *</label>
              <input type="text" formControlName="apellido" class="form-control form-control-custom"
                [class.is-invalid]="field('apellido').invalid && field('apellido').touched">
              @if (field('apellido').invalid && field('apellido').touched) {
                <div class="invalid-feedback">Apellido requerido (mín. 2 caracteres).</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Correo Electrónico *</label>
              <input type="email" formControlName="email" class="form-control form-control-custom"
                [class.is-invalid]="field('email').invalid && field('email').touched">
              @if (field('email').invalid && field('email').touched) {
                <div class="invalid-feedback">Email inválido.</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Contraseña *</label>
              <input type="password" formControlName="password" class="form-control form-control-custom"
                [class.is-invalid]="field('password').invalid && field('password').touched">
              @if (field('password').invalid && field('password').touched) {
                <div class="invalid-feedback">Mínimo 8 caracteres.</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Teléfono *</label>
              <div class="input-group">
                <select formControlName="prefijoTelefono" class="form-select" style="max-width: 155px;">
                  @for (country of countries; track country.code) {
                    <option [value]="country.dialCode">{{ country.code }} {{ country.dialCode }}</option>
                  }
                </select>
                <input type="tel" inputmode="numeric" formControlName="telefono" class="form-control form-control-custom"
                  placeholder="987654321" [class.is-invalid]="field('telefono').invalid && field('telefono').touched">
              </div>
              @if (field('telefono').invalid && field('telefono').touched) {
                <div class="text-danger small mt-1">Ingresa entre 6 y 12 dígitos, sin repetir el código de país.</div>
              }
            </div>
            <div class="col-md-6">
              <label class="form-label fw-semibold">Nacionalidad</label>
              <select formControlName="nacionalidad" class="form-select form-control-custom">
                @for (country of countries; track country.code) {
                  <option [value]="country.name">{{ country.name }}</option>
                }
              </select>
            </div>
          </div>

          <div class="d-grid gap-2 mt-4">
            <button type="submit" class="btn btn-primary-custom" [disabled]="loading()">
              @if (loading()) { <span class="loading-spinner me-2"></span> }
              <i class="fas fa-user-plus me-2"></i>Crear Cuenta
            </button>
          </div>
        </form>

        <div class="text-center mt-3">
          <button class="btn btn-link p-0 text-primary-custom" (click)="close.emit()" [disabled]="loading()">
            ¿Ya tienes cuenta? Inicia sesión aquí
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
